@startuml

actor Employee
participant "Pet" as Pet
participant "Owner" as Owner

Employee -> Pet: POST /owners/{ownerId}/pets/new {pet}
activate Pet
    Pet -> Pet: verify new pet data
    alt correct data
    Pet -> Owner: saveNewPet(pet)
    Pet -> Pet : save(pet)
    Pet --> Employee: return "redirect:/owners/{ownerId}"
    else incorrect data
    Pet --> Employee: error: invalid data
    end



@enduml
